### ISSUE TITLE
Directora o Director de Tecnología Civica [Laboratorio para la Ciudad]

### ISSUE THREAD

**Issue by miguelsalazar** [CodeandoMexico/chambas#10]
![labcdmx](https://user-images.githubusercontent.com/2068301/27664121-56121e36-5c2b-11e7-9109-52b80bc0a2e1.png)

# Directora o Director de Tecnología Civica

## Sobre el puesto 👾

Como Directora o Director de Tecnología Civica del Laboratorio para la Ciudad tendrás la oportunidad de ayudar a definir buenas prácticas de desarrollo de tecnología dentro del Gobierno de la Ciudad, hacer más eficientes los procesos de explotación y aprovechamiento de la información dentro del gobierno y para la ciudadania, ayudar a mejorar la transparencia y rendición de cuentas por medio de la liberación y el aprovechamiento de datos gubernamentales, y comprender cómo funciona el gobierno de la ciudad más de cerca. 

### Detalles 

* 🇲🇽 Ciudad de México
* 🏢 Presencial
* 🕐 Tiempo completo
* 📅 Agosto 2017
* 💸 $27,000 MXN netos (por honorarios)

### Responsabilidades 💻

* Implementar los programas y proyectos de innovación tecnológica de la Dirección General de Creatividad y de la Dirección Ejecutiva de Planeación y Proyectos Creativos que promuevan buenas prácticas, datos abiertos, transparencia proactiva y  gobierno abierto.
* Apoyar en el mantenimiento, soporte y actualización de herramientas digitales, aplicaciones y plataformas web. 
* Organizar los datos disponibles para su apertura y la información geográfica para mapeo, de acuerdo con los requerimientos técnicos y acuerdos interinstitucionales.

#### Adicionales

* Diseñar y mejorar las herramientas tecnológicas complementarias a las actividades del laboratorio.
* Proponer e implementar soluciones tecnológicas que apoyen la apertura de datos gubernamental en la ciudad de México.
* Proponer mejoras a los sistemas de recolección de datos de las distintas dependencias gubernamentales de la ciudad de México.
* Proponer mejoras a la automatización de liberación de datos de las distintas dependencias gubernamentales.
* Deberá tener disposición para comprender culturas organizacionales diversas y aprender en la administración pública, entusiasmo por los datos abiertos y la tecnología cívica.

### Lo que buscamos 💡

Idealmente, el o la Directora o Director de Tecnología Civica del Laboratorio para la Ciudad deberá tener experiencia con administración de servidores, desarrollo web, diseño de bases de datos, diseño y desarrollo de APIs y gestión de proyectos.

- [ ] Habilidades intermedias/avanzadas de desarrollo para aplicaciones web en lenguajes Ruby, Javascript y Python y frameworks como Ruby on Rails, Node, y React.
- [ ] Habilidades intermedias/avanzadas en HTML y CSS.
- [ ] Habilidades intermedias en DevOps.
- [ ] Habilidades intermedias/avanzadas en diseño y desarrollo de APIs.

### ¿Por qué aplicar? ❤️

* Tendrás la oportunidad de reforzar la comunidad de hacking cívico a través de eventos como Civic Hack Night y HackCDMX.
* Proponer nuevas ideas que podrán tener impacto en millones de personas.
* Ser parte de la comunidad global de #CivicTech a través de la participación oficial en eventos de [Code for All](http://codeforall.org).

## Sobre el Laboratorio para la Ciudad 🚀

El Laboratorio para la Ciudad es el área experimental del Gobierno de la Ciudad de México. El Laboratorio es un espacio de especulación y ensayo, donde lanzamos provocaciones que plantean nuevas formas de acercarse a temas relevantes para la ciudad, incubamos proyectos piloto y promovemos encuentros multidisciplinarios en torno a la innovación cívica y la creatividad urbana. El Laboratorio crea diálogos y complicidades entre gobierno, sociedad civil, iniciativa privada y organizaciones no gubernamentales con el propósito de reinventar, en conjunto, algunos territorios de ciudad y gobierno.

El Laboratorio reúne a personas de diferentes disciplinas y continuamente colabora con expertos nacionales e internacionales. Promueve de forma estratégica el capital creativo y el talento ciudadano de la Ciudad de México, vinculándolo con otras mentes e iniciativas brillantes en otras partes del mundo. En pocas palabras, el Laboratorio es un lugar híbrido y fluctuante, un vehículo experimental para materializar ideas y reimaginar, en conjunto, la ciudad (im)posible

### Nuestras redes ✉️
* [Website](http://labcd.mx)
* [GitHub](https://github.com/labplc)
* [Facebook](http://www.facebook.com/LabCDMX)
* [Twitter](http://www.twitter.com/LabCDMX)
* [Instagram](http://www.twitter.com/LabCDMX)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a diana [arroba] labcd [punto] mx e incluye:

* Tu currículum vitae actualizado.
* Tu portafolio de proyectos y/o GitHub.
* Un documento (en formato pdf) que respondas en una sola cuartilla a las siguientes preguntas: ¿Por qué me interesa ser el o la próxima CTO del Laboratorio para la Ciudad? ¿Qué habilidades, experiencias y conocimientos me hacen la o el candidato ideal para el puesto?

**Comment by imarban** [comment]
No me lo tomes a mal pero será muy difícil encontrar un CTO que se dedique de tiempo completo a Laboratorio para la Ciudad por 27,000 pesos mensuales pagados por honorarios. Deberían reconsiderar la oferta económica.

**Comment by ghost** [comment]
me explicas como funciona eso de los honorarios, tengo el perfil y un buen repo de referencia considero

**Comment by DianaSifuentesMunch** [comment]
Hola @IngPaz, el formato del contrato es que recibes 27 mil pesos libres mensuales y la institución se hace cargo de declarar tus impuestos. Cabe mencionar que bajo este esquema, eres tú quien se encarga de un seguro de gastos médicos, etc.

**Comment by ghost** [comment]
entiendo si no tengo problemas con eso del seguro, pudieras aun si la vacante ya se cubrió o cerró evaluar mi perfil de github por favor para algún otro puesto futuro? @DianaSifuentesMunch gracias

**Comment by DianaSifuentesMunch** [comment]
@IngPaz Hola Alfredo, la vacante no se ha llenado. Por favor envíanos lo que te pedimos más arriba vía correo electrónico para evaluar tu candidatura.

**Comment by DianaSifuentesMunch** [comment]
@imarban Hola Israel, gracias por tu comentario. En realidad la vacante es una combinación de conocimientos técnicos medianamente complejos y creatividad. Más allá de saber hacer todo tipo de Apps y plataformas, es saber resolver problemas técnicos a los que nos enfrentamos al implementar mecanismos de apertura gubernamental así como proponer formas eficientes y automatizadas para garantizar la sustentabilidad de estos mecanismos. Saludos!
