### ISSUE TITLE
Desarrollador Android para Multinf

### ISSUE THREAD

**Issue by Alba-DelaGarza** [CodeandoMexico/chambas#13]
#Desarrollador Android & Ruby

Multinf es una empresa tiene 5 años en el mercado que se especializa en el desarrollo de software, específicamente aplicaciones móviles, aplicaciones web y de escritorio.

### Detalles 

* 🇲🇽  Monterrey, NL.
* 🏢  Presencial 
* 🕐  Tiempo completo, 10:00 AM - 4:30 PM 
* 📅  Agosto 2017
* 💸  15,000.00 a 22,000.00 

### Responsabilidades 💻

* Colaborar en la planeación de proyectos de desarrollo de software 
* Desarrollo de aplicaciones Android (mobil, tv, wearables)
* Desarrollo con metodologías ágiles.
* Desarrollar en "multi-thread" cuidando el performance de las aplicaciones.

### Lo que buscamos 💡

- [ ] Desarrollo web con Ruby/Ruby on Rails (AngularJS deseable).
- [ ] Java (Kotlin deseable).
- [ ] Experiencia en testing de código así como desarrollar código "testeable".

### Beneficios ❤️

* Prestaciones de Ley:
* Vacaciones
* Prima Vacacional
* Aguinaldo
* Capacitaciones
* 100% declarado en el IMSS.

### Nuestras redes ✉️

* [Facebook](https://www.facebook.com/multinf/)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a albagarza@multinfmty.com

**Comment by mxcoder** [comment]
Hola @Alba-DelaGarza
Esta posición ya se ocupo? De ser así podrías cerrar el issue?
Si aun esta activo, seria bueno ponerle una fecha de actualización.
