### ISSUE TITLE
Desarrollador@ FullStack para webmatica.io

### ISSUE THREAD

**Issue by ghost** [CodeandoMexico/chambas#18]
# **Desarrollador FullStack**

### Detalles 

* 🇲🇽 Pachuca, Hgo.
* 🏢 Presencial con flexibilidad
* 🕐 Tiempo completo
* 📅 Inmediato
* 💸 A tratar

### Responsabilidades 💻

* Desarrollo fullstack y/o back end de aplicaciones.
* Desarrollo de front end de manera sincronizada con equipo de diseño.
* Soporte a servidores AWS y/o Google Cloud.

### Lo que buscamos 💡

- [ ] Desarrollo de Apps y plataformas basadas en web con arquitecturas centradas en RESTful API´s, backend con Node JS, Ruby o Python uso de frameworks Jinja2, Angular JS y bases de datos PostgreSQL y MongoDB.
- [ ] Profesionalismo e Interés en participar en el desarrollo de aplicaciones disruptivas.
- [ ] Experiencia para escribir código limpio, documentado y con pruebas.

### Beneficios ❤️

* Buen ambiente de trabajo.
* Flexibilidad de horario.
* Apoyo para el aprendizaje continuo.

## Sobre webmatica 🚀

webmatica es una empresa de tecnología con más de 20 años de experiencia en las TI. Estámos involucrados en soluciones de participación y "engagement" ciudadano con el objetivo de aprovechar el conocimiento colectivo y apoyar a la solución de problemáticas sociales.

Buscamos entusiastas que quieran formar parte de un equipo multidisciplinario y participar en el desarrollo de aplicaciones y tecnologías disruptivas.

### Nuestras redes ✉️

* [GitHub](http://www.github.com/CodeandoMxico)
* [Facebook]https://www.facebook.com/webmatica.io/
* [Twitter]https://twitter.com/_webmatica

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a contacto@webmatica.io o manda un Inbox en nuestras redes sociales.

**Comment by mxcoder** [comment]
Hola @asanamx 
Esta posición ya se ocupo? De ser así podrías cerrar el issue?
Si aun esta activo, seria bueno ponerle una fecha de actualización.

**Comment by ghost** [comment]
Aunque ya se contrató gente la posición sigue disponible para otros developers.

**Comment by almarngl** [comment]
¡Hola @asanamx! ¿Esta oportunidad sigue vigente?

**Comment by ghost** [comment]
Si todavía, gracias.
