### ISSUE TITLE
Worky - Desarrollador frontend

### ISSUE THREAD

**Issue by julsdelatierra** [CodeandoMexico/chambas#20]
# Desarrollador frontend para startup fintech

Producto fintech para recursos humanos con la misión de mejorar el bienestar financiero de los empleados y automatizar procesos en las pymes.

## Sobre el puesto 👾

Estamos en fase de escalamiento, por lo que estamos incrementando nuestro equipo y necesitamos programador frontend que ame el UI/UX, para ayudar a mejorar nuestro producto.

### Detalles 

* 🇲🇽 Ciudad de México
* 🏢 Presencial
* 🕐 Tiempo completo
* 📅 1/Mar/2018
* 💸 $ 20K - 25K netos

### Responsabilidades 💻

* Programar con la mayor calidad posible.
* Compartir tus opiniones, ideas y conocimiento.
* Adquirir sentido de propiedad sobre el producto.
* Ayudar a resolver problemas dentro de nuestra plataforma.

### Lo que buscamos 💡

- Pro-activo.
- Sentido común.
- Vue o React o Angular.
- HTML + CSS.
- Flux o Vuex.
- Experiencia integrando APIs.

### Beneficios ❤️

* Flexibilidad de horario y ubicación.
* Una reluciente Macbook Air de 13".
* Monitor de trabajo.
* Acciones de la empresa.
* Café ilimitado.
* Cerveza ilimatada.

## Sobre Worky 🚀

Trabajamos sobre objetivos, somos una empresa pequeña donde se valora tu iniciativa y puedes aportar mucho al producto y al equipo, además puedes impactar en todas las áreas de la empresa.

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a jul@worky.mx

**Comment by mxcoder** [comment]
Hola @jcebXD 
Esta posición ya se ocupo? De ser así podrías cerrar el issue?
Si aun esta activo, seria bueno ponerle una fecha de actualización.
