### ISSUE TITLE
Technicolor - Intern in Robotics Process Automation (RPA) Development

### ISSUE THREAD

**Issue by RPAFSSC** [CodeandoMexico/chambas#25]
Robotics Process Automation (RPA) Development Intern

Technicolor is looking for university students who are excited about learning and trying out new technologies. We need technically minded individuals who have great analytical and problem-solving skills and the ability to implement them as well. Here, you’ll get to work with Microsoft’s SharePoint 2013, Web Applications, SAP, Oracle and JBA ERPs. 

* 🇲🇽 Guadalajara Sur - Santa Anita
* 🏢 Presencial
* 🕐 Tiempo completo o tiempo parcial
* 📅 Inmediato
* 💸 A Tratar

### Responsabilidades 💻

The Robotics Process Automation (RPA) Development intern role works with our internal customers throughout the organization.  This position requires excellent facilitation skills, an exceptional process improvement background and superb time-management skills. 

### Lo que buscamos 💡

• Be in the last three semesters of university in Computer Science, Information Technology, Software Development or other related fields. 
• Have at least one year of experience programming (school and/or professional projects) in one or more development languages and be willing to learn Automation Software Programming. 
• Know the basic phases of the software development life cycle: business requirement gathering, solution design, development, testing, documentation and delivery to operations. 
• Track and document efficiency delivery and validate utilization levels post implementing automation projects. 
• Have at least 20 hours available per week: Monday through Friday either from 9am to 1pm or from 2pm to 6pm. 

### Beneficios ❤️

The student will have the opportunity to work with several different platforms and frameworks. You will work directly with business process owners, stakeholders and technical analysts to define IT services, proactively identify, develop, and build-in process improvement opportunities and manage the service into production.

## Sobre { nombre de la empresa u organización } 🚀

At Technicolor, we unite creativity with technology to push the boundaries of what entertainment can be

### Nuestras redes ✉️

https://www.technicolor.com/

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, envía CV a eduardo.gamino@technicolor.com

**Comment by almarngl** [comment]
Hola @RPAFSSC ¿podemos cerrar este issue o siguen en la búsqueda?

**Comment by RPAFSSC** [comment]
Hola,

Muchas gracias, ya se puede cerrar.

Saludos,


Eduardo Gamino
FSSC Quality Process Improvement Manager
www.technicolor.com<http://www.technicolor.com>
[cid:9C7DE145-FB87-4213-A253-3946C6A84C5F]
