### ISSUE TITLE
Ideas sobre moderacion y alcance del repo.

### ISSUE THREAD

**Issue by mxcoder** [CodeandoMexico/chambas#26]
Hola Codeando.
Quiero abrir este hilo para discutir un par de ideas sobre este repo de chambas:

1. Seria bueno mantener los issues frescos, yo me ofrezco a llevar una ligera moderación para ello, pero cualquiera podría hacerlo. Y podríamos usar algún tipo de labels o tags para marcar los issues según su "edad".
1. Cual es el alcance que se quiere de este repo y las ofertas? si queremos que mucha gente lo conozca tal vez podríamos hacer uso de algunas cuentas de Twitter o de LinkedIn para publicitar las ofertas. Pero no estoy seguro si se quiere mantener solo para la comunidad.

**Comment by the-vladman** [comment]
De acuerdo en eso. Se podria tambien acercar con algunas startups que ya tienen como un talent search

**Comment by almarngl** [comment]
¡Gracias a ambos! Son buenos comentarios, sobre sus puntos:

1. De acuerdo, si tú te ofreces @mxcoder te lo agradecería, después podríamos ir rotando a la persona que nos ayude en esto.
2. La idea de este repo es que aliados y empresas de tecnología cívica se puedan acercar a la comunidad. Le damos publicidad a través de FB y Twitter, pero podríamos hacer un esfuerzo más grande para que más iniciativas (como lo que menciona @the-vladman) pongan acá sus vacantes.

**Comment by mxcoder** [comment]
Excelente @almarngl . Avísame como le hacemos entonces para (1). En (2), te refieres a cuentas "oficiales" o personales? Si lo primero, cuales son?

**Comment by germancosio** [comment]
Hola!, me parece una excelente idea el moderar este repo para mantenerlo foco y actualizado, @mxcoder yo me ofrezco para echarte la mano en lo que necesites.

**Comment by almarngl** [comment]
Para el (1) creo que podemos rotar cada mes o cada dos meses. ¿Qué piensan @germancosio y @mxcoder? Podemos definir que cada tres semanas, quien haya abierto el issue necesita hacer update sobre si sigue abierto. 

Sobre el (2) le damos difusión en las cuentas oficiales de Codeando y el canal de chambas.

**Comment by mxcoder** [comment]
Hola, yo no tengo problema, tengo disponibilidad para ayudar.
Y concuerdo, con un par de reglas claras sobre la vigencia de las publicaciones estaría super bien.

@almarngl cuales son las cuentas oficiales ? :)

**Comment by germancosio** [comment]
Tampoco tengo ningún problema :) por que medio podemos discutir las reglas propuestas?

**Comment by miguelsalazar** [comment]
Cerrando por inactividad.
