### ISSUE TITLE
React Native Developer

### ISSUE THREAD

**Issue by ferlopezm94** [CodeandoMexico/chambas#27]
# React Native Developer

En [Higia Technologies](https://www.higia.tech) estamos buscando un desarrollador que tenga la capacidad de analizar, diseñar, implementar, poner en producción y monitorear interfaces de usuario web y móviles, usando tecnologías frontend modernas.

### Detalles 

* 🇲🇽 { Puebla / Monterrey }
* 🏢 { Presencial }
* 🕐 { Tiempo completo }
* 📅 { ASAP }
* 💸 { 20-30k netos }

### Responsabilidades 💻

* Desarrollo de interfaces de usuario para web, Android y iOS
* Diseño y desarrollo de pruebas automatizadas 
* Diseñar y desarrollar una estrategia de Continuous Integration/Deployment
* Participar en diseño y revisión de código

### Lo que buscamos 💡

- Experiencia construyendo Single Page Applications
- Experiencia con el ecosistema de React y React Native
- Experiencia con Jest o frameworks similares para pruebas automatizadas
- Sólido entendimiento del ciclo de vida de aplicaciones web, incluyendo testing, deploying y monitoring
- Experiencia integrando APIs

### Beneficios ❤️

* Flexibilidad de horario
* Buen ambiente de trabajo
* Convivir con personas extraordinarias en áreas de Hardware, Software y Machine Learning

## Sobre Higia Technologies 🚀

Somos una startup que se encuentra desarrollando un dispositivo no invasivo y portátil para la evaluación de riesgo de cáncer de mama. 

Estamos buscando a uno de los mejores desarrolladores en React/React Native que nos ayude a revolucionar la temprana detección de cáncer de mama.

### Nuestras redes ✉️

* [Web](https://www.higia.tech)
* [Facebook](https://www.facebook.com/HigiaTech/)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a jobs@higia.tech.

**Comment by almarngl** [comment]
¡Hola @ferlopez94! ¿Esta posición ya está cubierta? ¿Podemos cerrar el issue?

**Comment by ferlopezm94** [comment]
¡Qué tal! Desafortunadamente esta vacante aún no está cubierta.

**Comment by bntzio** [comment]
@ferlopez94 Es posible remoto?

**Comment by ferlopezm94** [comment]
@bntzio podríamos evaluarlo, pero de preferencia buscamos presencial. Como sea, compártenos tu CV si gustas a jobs@higia.tech.

**Comment by bntzio** [comment]
@ferlopez94 Ok 😄
