### ISSUE TITLE
Producción de Videos Educativos Cortos (estilo MOOC) sobre "Justicia Abierta"

### ISSUE THREAD

**Issue by dino-at-thegovlab** [CodeandoMexico/chambas#28]
# Producción de Videos Educativos Cortos (estilo MOOC) sobre "Justicia Abierta"

The GovLab, a nonprofit action research center housed at NYU, is looking for an individual or team, to undertake a video production project this fall.

We are creating a Spanish and English language version of a MOOC on judicial transparency or Open Justice.

The course contains 10 video-based modules, where each module comprises:
- A 10-minute video of a single lecturer shot in New York;
- A 10-minute interview of a practitioner recorded via the Web; and
- A 5-minute screen cast of a relevant platform with voiceover.

## Sobre el puesto 👾
For the lectures, we are interested in quote for single camera shoots and/or voice over with slides for the lectures. Lectures will include the editing in of interstitial slides and the optional preparation of animations to illustrate key concepts. Interviews will involve production and editing of the interviews conducted either via the web or editing of videos shot on location. Demos are screencasts with annotation. 

### Detalles 
The GovLab, a nonprofit action research center housed at NYU, is looking for an individual or team, to undertake a video production project this fall.

We are creating a Spanish and English language version of a MOOC on judicial transparency or Open Justice.

The course contains 10 video-based modules, where each module comprises:
- A 10-minute video of a single lecturer shot in New York;
- A 10-minute interview of a practitioner recorded via the Web; and
- A 5-minute screen cast of a relevant platform with voiceover.

For the lectures, we are interested in quote for single camera shoots and/or voice over with slides for the lectures. Lectures will include the editing in of interstitial slides and the optional preparation of animations to illustrate key concepts. Interviews will involve production and editing of the interviews conducted either via the web or editing of videos shot on location. Demos are screencasts with annotation. 

In detail, we will need the following services:

*1. Filming*
- Vendor will provide the sound, lighting and filming equipment to shoot the videos at our offices in New York City.
- The modules will be launched weekly beginning in mid-October. Thus filming will likely need to continue between October-November to complete.

*2. Editing*
- The Vendor will edit and organize the final clips at GovLab's direction.
- The Vendor will provide a rough cut and up to two edits of the module video in the project time frame.
- The Vendor will provide a transcript with all the content of each video. 
- The Vendor will provide hi-res source files of the final video for uploading.

*3. Final Copies*
- The Vendor assigns all present and future rights to the materials produced during the project to the GovLab.
- The Vendor will be credited in the final product and such credit will be according to GovLab’s design preferences.

*PROPOSAL REQUIREMENTS*
- Introduction summarizing you/r company’s project history and relevant experience.
- Examples of past projects, preferably of a similar size and scope.
- Proposed budget for the project with filming/editing fees listed separately from equipment and installation costs.
- Proposed production schedule for the project, including project stages, milestones and payments (modules will be launched weekly beginning in mid-October).
- Optional supporting materials of you/your firm’s choosing.
- At least three references from previous clients
- *Submission Deadline: August 30, 2018.*

* 🇲🇽 {Nueva York}
* 🏢 { Presencial y remoto }
* 🕐 { Freelance }
* 📅 { Principios de Septiembre }
* 💸 { TBD }

### Nuestras redes ✉️

* thegovlab.org
* govlabacademy.org

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a {dinorah@thegovlab.org}

**Comment by miguelsalazar** [comment]
Cerrando por inactividad.
