### ISSUE TITLE
Desarrollador Geo medio tiempo

### ISSUE THREAD

**Issue by jdeltoro1973** [CodeandoMexico/chambas#29]
# Desarrollo de GeoPortal web con tecnologías libres y abiertas

Estamos buscando uni desarrolladori Geo (medio tiempo) para un GeoPortal utilizando teconolgías libres y abiertas.

El GeoPortal ya está en desarrollo y estamos utilizando Laravel, PHP, Javascript, Jquery y OpenLayers

## Sobre el puesto 👾
Nos gustaría contar con uni personi con ganas de aprender o ampliar su conocimiento en el uso y desarrollo de tecnologías web para el manejo y visualización de mapas, este trabajo puede ser presencial o remoto
### Detalles 

* 🇲🇽 Guadalajara, Jalisco
* 🏢 Presencial o remoto
* 🕐 Medio tiempo
* 📅 1 de agosto
* 💸 { Sueldo }

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a jdeltoro1973@gmail.com

**Comment by miguelsalazar** [comment]
Cerrando por inactividad.
