### ISSUE TITLE
Intern de Comunicación y Contenido

### ISSUE THREAD

**Issue by almarngl** [CodeandoMexico/chambas#30]
# Internship de Comunicación y Contenido

Codeando México es una comunidad de hackers que busca generar nuevas formas de participación ciudadana a través de la tecnología. Estamos buscando un persona emocionada por el potencial de la tecnología para mejorar nuestras ciudades, que genere contenido e implemente estrategias de comunicación para contar nuestras historias y proyectos. 

Si eres un/a estudiante, con disponibilidad para colaborar de 15 a 20 horas semanales, que esté cursando del 6to semestre en adelante de las carreras de Comunicación y Medios Digitales, Diseño Gráfico, Animación y Arte Digital o afines, ¡queremos saber de ti! 

### Detalles 

* 🇲🇽 { Guadalajara }
* 🏢 { Presencial o remoto }
* 🕐 { Medio tiempo }
* 📅 { 01 de septiembre 2018 }
* 💸 { $3,000 }

### Responsabilidades 💻

* Implementar la estrategia de comunicación de la organización 
* Búsqueda de contenidos 
* Generación de contenidos visuales i.e. GIFs, imágenes, videos 
* Manejo de redes sociales 
* Generar y rebotar ideas de comunicación con el resto del equipo 

### Lo que buscamos 💡

- [ ] Ideas claras al hablar y escribir 
- [ ] Habilidades de edición de vídeo y fotografía, así como diseño gráfico 
- [ ] Emoción por la tecnología como herramienta para generar cambios 
- [ ] Iteración, estás constantemente encontrando formas de mejorar tus procesos 
- [ ] Action-driven: eres independiente, propones nuevas ideas y las implementas 

¡Pero estamos abiertos a cosas nuevas! Estas habilidades son enunciativas, más no limitativas. Queremos que el ser parte del equipo sea un proceso retador y de aprendizaje, no tengas miedo de aplicar a la oportunidad incluso si no eres un experto o consideras que alguna de las habilidades no está tan desarrollada, podemos aprender juntos.  

### Beneficios ❤️

* Conoce personas y proyectos increíbles de todo el país
* Queremos apoyarte a desarrollar tus habilidades, buscaremos mentores que te ayuden a lograr tus objetivos
* Trabaja con nosotros desde nuestras oficinas en Guadalajara
* Acceso a libros y conocimiento que te ayuden a mejorar tus habilidades
* Retroalimentamos de manera clara y directa, enfocándonos en generar un aprendizaje

## Sobre Codeando México 🚀

Codeando México es una comunidad de hackers que busca generar nuevas formas de participación ciudadana a través de la tecnología. Buscamos gobiernos que hagan mejor uso de la tecnología; y aumentar la capacidad de incidencia de la ciudadanía. 
 
Colaboramos con personas de todos los perfiles: activistas, periodistas, funcionarios públicos; diseñadores. Cualquiera que comparta nuestros principios, valores y código de conducta puede ser parte de esta comunidad. 

### Nuestras redes ✉️

* [GitHub](http://www.github.com/CodeandoMexico)
* [Facebook](http://www.facebook.com/CodeandoMexico)
* [Twitter](http://www.twitter.com/codeandomexico)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a {equipo@codeandomexico.org} y manda tu CV, un párrafo sobre por qué te interesa trabajar en Codeando México y tu portafolio o reel, en caso de contar con uno.

**Comment by miguelsalazar** [comment]
Cerrando por inactividad.
