### ISSUE TITLE
Backend/DevOps Developer

### ISSUE THREAD

**Issue by ferlopezm94** [CodeandoMexico/chambas#32]
# Backend/DevOps Developer

En [Higia Technologies](https://www.higia.tech) estamos buscando un desarrollador backend con experiencia en DevOps que nos ayude a revolucionar la detección temprana de cáncer de mama.

### Detalles 

* 🇲🇽 { Puebla }
* 🏢 { Presencial }
* 🕐 { Tiempo completo }
* 📅 { ASAP }
* 💸 { 20-30k netos }

### Responsabilidades 💻

- Diseñar, implementar y mantener la infraestructura Cloud
- Ejecutar implementaciones de aplicaciones a través CI / CD pipelines
- Monitorear y diagnosticar el estado de los servicios desplegados
- Optimizar los cuellos de botella de rendimiento en despliegues de aplicaciones
- Aplicar las mejores prácticas en seguridad de aplicaciones
- Diseñar e implementar estrategias de respaldo y recuperación

### Lo que buscamos (experiencia en)💡

* Amazon Web Services (plantillas de Cloudformation, distribuciones Cloudfront, S3, RDS, API Gateway, Lambda)
* Implementación de tuberías CI / CD
* Arquitecturas escalables y sin servidor
* Node.js y Typescript
* Bases de datos SQL relacionales (PostgreSQL) y NoSQL
* Protocolo HTTP
* GraphQL
* Buenas prácticas de Cloud Security
* Copia de seguridad y recuperación de desastres
* Implementación de pruebas automatizadas

### Beneficios ❤️

* Flexibilidad de horario
* Buen ambiente de trabajo
* Convivir con personas extraordinarias en áreas de Hardware, Software y Machine Learning

## Sobre Higia Technologies 🚀

Somos una startup que se encuentra desarrollando un dispositivo no invasivo y portátil para la evaluación de riesgo de cáncer de mama.

### Nuestras redes ✉️

* [Web](https://www.higia.tech)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, envíanos tu CV a jobs@higia.tech.

**Comment by alexter42** [comment]
Remoto?

**Comment by ferlopezm94** [comment]
@alexter42 podríamos evaluarlo. Por favor compártenos tu CV a jobs@higia.tech.

**Comment by almarngl** [comment]
@ferlopezm94 ¿ya está cerrada esta vacante?
