### ISSUE TITLE
Python Senior Bilingüe

### ISSUE THREAD

**Issue by fcopantoja** [CodeandoMexico/chambas#33]
# Python Senior Bilingüe

SpotOn es una plataforma de pagos, marketing y lealtad de rápido crecimiento. Hemos creado herramientas fáciles de usar para que las empresas aumenten sus ingresos y los conecten con sus clientes mediante el uso de recompensas, ofertas, comentarios en línea y análisis de datos.

## Sobre el puesto 👾
Como ingeniero de software en SpotOn, se te asignará la tarea de trabajar junto con un equipo sólido de ingenieros de back-end, full-stack y frontend para construir software web basado en componentes, utilizando las mejores prácticas modernas y un enfoque de "mantenerlo en serio simple" siempre que sea posible. Actualmente estamos creciendo y expandiéndonos hacia nuevos mercados verticales, tendrás la oportunidad de crear nuevas funciones y características en nuestra línea de productos.

### Detalles 
Se requiere:
- Inglés avanzado/intermedio
- Más de 3 años de experiencia con Python
- Amplia experiencia usando Django
- PEP8
- Experiencia desarrollando y consumiendo API
- Habilidades de base de datos SQL

Puntos de bonificación por
- Experiencia MongoDB
- Experiencia Con Twisted
- Async en Python 3.5+
- ES6 y ReactJS
- DevOps: Ansible y AWS

Sobre la Empresa:
- Horas flexibles en un ambiente de trabajo divertido y relajado.
- Creciendo rápidamente en un mercado con espacio para crecer.
- Ubicación céntrica, a menos de 5 minutos de varias fuentes de transporte público.

* 🇲🇽 Ciudad de México
* 🏢 Presencial
* 🕐 Tiempo completo
* 💸 45,000 - 60,000

### Beneficios ❤️
* Macbook Pro o el equipo que necesites
* Monitor 4K
* Horarios flexibles

### Nuestras redes ✉️
* [Página web](http://www.spoton.com)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, manda tu CV en inglés a francisco@spoton.com

**Comment by almarngl** [comment]
@fcopantoja ¿sigue abierta esta vacante?

**Comment by fcopantoja** [comment]
@almarngl Sí, sigue abierta.
