### ISSUE TITLE
DevOps

### ISSUE THREAD

**Issue by leodc** [CodeandoMexico/chambas#35]
# DevOps

Hola ! actualmente en la Estrategia Digital Nacional estamos buscando 1 DevOps que nos ayude a generar estrategias para CI/CD así como para la automatización de procesos (recuperación de fallos, Infrastructure on demand)

### Detalles 

* 🇲🇽 { Ciudad de México }
* 🏢 { Presencial }
* 🕐 { Tiempo completo }
* 📅 { Fecha de ingreso: inmediata }
* 💸 { $38,000.00 }

### Responsabilidades 💻

* Despliegue y configuración de servidores (IaC).
* Despliegue de aplicaciones y bases de datos.
* Automatización de procesos en servidores.
* Apoyo en la definición de estrategias para el monitoreo y recuperación de errores 
* Apoyo en la definición para el despliegue e integración continua de aplicativos.
* Evaluar pipelines de proyectos y sugerir arquitecturas, stacks y servicios para la mejora.
* Automatización de pruebas.
* Definición de estrategias de solución a problemas de infraestructura.

### Lo que buscamos 💡

- [ ] Lenguajes de programación: bash / perl / python
- [ ] Infraestructura: Terraform, Chef, Ansible, Puppet
- [ ] Integración continua: Jenkins
- [ ] Contenedores y orquestación: Kubernetes, Docker
- [ ] Monitoreo: Grafana, Prometheus, Datadog

### Beneficios ❤️

* Generar impacto a nivel nacional 
* Esquema flexible de trabajo
* Participación e implementación de soluciones a problemas actuales del país

## Sobre Estrategia Digital Nacional 🚀

La Estrategia Digital Nacional (EDN) es el plan de acción que se esta implementando para construir un México Digital, en el que la tecnología y la innovación contribuyan a alcanzar las grandes metas de desarrollo del país.

### Nuestras redes ✉️

* [GitHub mxabierto](https://github.com/mxabierto)
* [Facebook](https://www.facebook.com/datosgobmx)
* [Twitter](https://twitter.com/DatosGobMX)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a leonel.castaneda@datos.mx.

**Comment by almarngl** [comment]
@leodc ¿ya cubrieron esta vacante? Para cerrar el issue :)
