### ISSUE TITLE
Científico de datos para Opi Analytics

### ISSUE THREAD

**Issue by yuririavila** [CodeandoMexico/chambas#38]
**Científico de datos**

Buscamos a un/a data scientist con la capacidad para recopilar y analizar variables útiles según insights propios y del equipo. Nuestro/a candidato/a ideal puede realizar el entrenamiento, evaluación e implementación de modelos; desarrollar y generar variables nuevas para modelos presentes y a futuro; expresar objetivamente ideas y recomendaciones sobre features o herramientas que puedan ser útiles.

### Detalles 

* 🇲🇽 Ciudad de México 
* 🏢 Presencial 
* 🕐 Tiempo completo
* 📅 Cualquier momento 
* 💸 20 mil -30 mil netos dependiendo experiencia

### Lo que buscamos 💡

- [ ] Comprensión y expresión de conceptos abstractos (lógicos/matemáticos)
- [ ] Traducción de problemas a fuentes y metodologías.
- [ ] Capacidad para interpretar e identificar problemas en los resultados y metodologías a través del planteamiento de pruebas intuitivas/técnicas.
- [ ] Manejo de datos en R o Python (cargar, visualizar/interpretar, transformar, extraer/justificar conclusiones).
- [ ] Capacidad funcional de terminal Linux.
- [ ] Editor de texto en servidor remoto como vim, nano.
- [ ] Manejo de herramientas para procesamiento en la nube: EC2, S3, Databricks, Blob Storage, Data Factory.
 - [ ] git/github (clone, add, commit, branch, merge, push, pull).
 - [ ] Conocimiento de SQL.
 - [ ]  Jupyter notebooks.
 - [ ]  Python: expresiones, funciones, tipos, Clases, programación orientada a objetos básica, context managers e IO (lectura de archivos y peticiones https).
- [ ] Pandas, numpy y Pyspark: lectura de datos, transformaciones de tablas, agregaciones, limitaciones, identificación y solución de problemas.
- [ ]     Dominio en el manejo de los siguiente archivos: .csv, excel, .json, parquet.
- [ ]     Manejo de dependencias y paquetes de python

### Beneficios ❤️
    
- [ ]     Salario competitivo, dependiente de experiencia y formación
- [ ]     Prestaciones de Ley
- [ ]     Afiliación al IMSS e INFONAVIT
- [ ]     Bono anual sobre ventas de la empresa con base en el desempeño del colaborador
- [ ]     Plan de adquisición de acciones de la empresa (stock-option plan)
- [ ]     Seguro de gastos médicos mayores
- [ ]     Seguro de vida

## Sobre **Opi Analytics** 🚀

OPI es una empresa de tecnología que ayuda a instituciones públicas y privadas a tomar decisiones informadas a través de algoritmos predictivos y sistemas de soporte de decisión.

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, manda tu CV con el asunto "Oferta científico de datos" a j.sanchez@opianalytics.com

**Comment by almarngl** [comment]
@yuririavila ¿ya está cerrada esta vacante?
