### ISSUE TITLE
Analista de Datos para Cómo Vamos, Nuevo León

### ISSUE THREAD

**Issue by CVNL** [CodeandoMexico/chambas#40]
# Analista de Datos en Cómo Vamos, Nuevo León

Buscamos a una persona comprometida con su comunidad y especialista en la exploración, el análisis y la generación de datos.

### Detalles 

* 🇲🇽 Monterrey, Nuevo León
* 🏢 Presencial
* 🕐 Tiempo completo
* 📅 15 de abril
* 💸 $20,000 - $23,000 (sueldo inicial)

### Responsabilidades 💻

* Sistematizar, actualizar y hacer análisis de bases de datos con información sobre diferentes temas públicos
* Realizar actividades y activaciones para socializar el uso de datos por diferentes audiencias (periodistas, estudiantes, OSCs)
* Participar en investigaciones con el objetivo de entender mejor temas de interés público y aspectos clave del desempeño gubernamental local

### Lo que buscamos 💡
- Experiencia de 1  2 años en exploración de datos
- Manejo de STATA y R
- Experiencia en áreas de investigación
- Una persona apasionada por los datos, con la creencia de que son un motor de cambio para tomar mejores decisiones públicas y, desde la sociedad civil, impulsar mejores gobiernos 
- Curiosidad y creatividad para resolver problemas y plantear alternativas para generar nuevos datos o encontrar formas alternativas de medir fenómenos sociales
- Convicción en que los datos deben ser para todos y deseo de que cada vez más gente conozca y exija la apertura de sus gobiernos.

### Beneficios ❤️

* Un trabajo con gran impacto en la comunidad
* Oportunidad de crecimiento laboral y desarrollo profesional
* Flexibilidad y un gran ambiente de trabajo

## Cómo Vamos, Nuevo León

En Cómo Vamos, Nuevo León buscamos generar investigaciones y evaluaciones que contribuyan a tener un mejor debate público sobre temas críticos y gobiernos más eficientes y confiables. 

### Nuestras redes ✉️

* [Cómo Vamos] (http://www.comovamosnl.org )
* [Facebook](http://www.facebook.com/ComoVamosNL)
* [Twitter](http://www.twitter.com/comovamosnl)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a lgarza@comovamosnl.org y/o reclutamiento@consejocivico.org.mx

**Comment by almarngl** [comment]
@CVNL ¿sigue abierta esta vacante?
