### ISSUE TITLE
Web Dev en la Agencia Digital de Innovación Pública, CDMX - Ruby, Python o PHP con framework

### ISSUE THREAD

**Issue by basicavisual** [CodeandoMexico/chambas#41]
# Web Developer - Backend

¡Buscamos Web Dev para hacer aplicaciones de Civic Tech desde gobierno en la CDMX!

## Sobre el puesto 👾

Buscamos Civic Hacker de Ruby, Python o PHP para unirse al equipo que desarrolla las soluciones de gobierno para toda la Ciudad de México. Nuestro equipo en la Agencia Digital de Innovación Pública, el cual responde directamente a la Jefa de Gobierno, se ocupa de construir las herramientas que usan las personas de la ciudad. Desde las apps para ver la temperatura, los recorridos del metrobús, los reportes ciudadanos, hasta los proyectos de reconstrucción, voluntariado en caso de desastres, simplificación de trámites, participación y demás. La persona que aplique a este puesto estaría trabajando sobre diversos proyectos de la agencia en el equipo de desarrollo  

### Detalles 

* 🇲🇽 { CDMX }
* 🏢 { Presencial }
* 🕐 { Tiempo completo }
* 📅 { Entrevistas abiertas }
* 💸 { A discutir en la entrevista }

### Responsabilidades 💻

* { Desarrollar y mantener otras aplicaciones web de la Agencia en Ruby, Python o PHP }

### Lo que buscamos 💡

- [ ] { Web developer en Ruby, Python o PHP con conocimiento de frameworks como Rails, Django o Laravel } 
- [ ] { Scrum o Agile }
- [ ] { Se aprecia conocimiento de HTML, CSS y Vanilla JS }
- [ ] { Proactivo, autodidacta, no le da miedo preguntar }
- [ ] { Amas el civic tech y quieres impactar con tu trabajo a mucha gente }

## Sobre la { Agencia Digital de Innovación Pública } 🚀

{ Somos la organización gubernamental encargada de digitalizar y eficientizar el gobierno de la Ciudad de México. Construímos aplicaciones o mejoramos las existentes. Eficientizamos trámites. Creamos nuevos canales de comunicación que permitan a los ciudadanos comunicarse más fácilmente con el gobierno. Simplificamos las partes burocráticas que podemos. Le damos herramientas a los ciudadanos para informarse y participar. }

### Nuestras redes ✉️

* [Facebook](http://www.facebook.com/laagenciacdmx)
* [Twitter](http://www.twitter.com/laagenciacdmx)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a alejandra.gonzalez@cdmx.gob.mx

**Comment by almarngl** [comment]
@ponentesincausa ¿sigue abierta la vacante?

**Comment by basicavisual** [comment]
Sigue abierto. Ya tenemos gente pero buscamos más. Lo voy a ampliar a otros lenguajes.

**Comment by almarngl** [comment]
@ponentesincausa ¿ya puedo cerrar este issue?
