### ISSUE TITLE
Web Designer (UI/UX)

### ISSUE THREAD

**Issue by ferlopezm94** [CodeandoMexico/chambas#42]
# Web Designer (UI/UX)

At Eva we are looking for a web designer who has the ability to design and implement crisp user interfaces using modern web technologies.

If you're a passionate web designer looking to make an impact by crafting pixel perfect and excellent user interfaces, we want to hear from you.
### Detalles 

- 🇲🇽 { Puebla }
- 🏢 { Presencial (se puede contemplar el trabajo remoto)}
- 🕐 { Tiempo completo }
- 📅 { ASAP }
- 💸 { 20-30k netos }

### Responsabilidades 💻

- Design and develop from the ground up a world-class e-commerce platform
- Maintain, improve and push forward our internal web apps design
- Transform the main Eva web site (https://evatech.co) into a high performant and good looking site with strong UX and UI principles
- Make sketch designs a reality using HTML and CSS (from artboards to dom) 

### Lo que buscamos 💡

- High proficiency and expert knowldge in HTML and CSS
- Ability to work under pressure (we're a startup)
- Strong understanding of how the DOM works
- Sufficient JavaScript knowledge to interact with DOM elements
- Aptitude to independently learn new technologies
- Knowledge of CSS pre-processors such as SASS, LESS or Stylus
- You apply OOCSS, BEM or SMACSS methodologies in your designs
- Always build sites using semantic markup

### Bonus points ✨

- Experience building SPAs such as React, Vue or Angular
- Experience integrating RESTful APIs
- Have heard about or tried CSS in JS
- Used Gulp or Webpack before
- Knowledge and interest in SEO
- Illustrator, Sketch or Figma experience (eye for design)
- CSS and JS animations (GSAP)
- Understand and can work with SVG
- Version control experience (Git/Gitlab/GitHub)

### Beneficios ❤️

- Flexibilidad de horario
- Buen ambiente de trabajo
- Convivir con personas extraordinarias en áreas de Hardware, Software y Machine Learning

## Sobre Eva  🚀

Somos una startup que se encuentra desarrollando un dispositivo no invasivo y portátil para la evaluación de riesgo de cáncer de mama.

### Nuestras redes ✉️

* [Web](http://evatech.co)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, envíanos tu CV a fernando.lopez@evatech.co.

**Comment by almarngl** [comment]
Hola @ferlopezm94 ¿puedo cerrar este issue?
