### ISSUE TITLE
Líder de comunidad en Codeando México

### ISSUE THREAD

**Issue by almarngl** [CodeandoMexico/chambas#44]
## Sobre el puesto 👾

Codeando México es una comunidad de hackers que busca resolver problemas públicos y generar nuevas formas de participación ciudadana a través de la tecnología. Somos una comunidad abierta y distribuida con integrantes que participan desde cualquier lugar a través de nuestros espacios digitales. Adicionalmente, tenemos comunidades locales en 5 ciudades del país.

Queremos crecer y conformar la red de hacking cívico más grande de América Latina. ¡Estamos buscando una persona que nos ayude a construirla!

Invitamos a personas de perfiles, experiencias e identidades diversas a aplicar.

### Detalles 

* 🇲🇽 México
* 🏢 Remoto
* 🕐 Tiempo completo
* 📅 1 de agosto
* 💸 $24,000 

### Responsabilidades 💻

*Coordinar el componente de comunidad en todos los proyectos de la organización
*Fomentar el intercambio de conocimiento y la replicación de proyectos en la comunidad
*Diseñar e implementar estrategias para crecer y fortalecer el engagement de la comunidad
*Dar seguimiento constante a las actividades que realizan nuestras brigadas 
*Ser el principal punto de contacto entre la comunidad y el core-team
*Mapear y facilitar posibilidades de colaboración con otras comunidades tecnológicas

### Lo que buscamos 💡

- [ ] Experiencia: Has estado en algún rol de coordinación de comunidad y trabajando con equipos multidisciplinarios. Tienes la capacidad de generar e implementar estrategias para fortalecer y crecer una comunidad. Es un gran plus si has trabajado en proyectos o iniciativas de tecnología cívica y/o datos.
- [ ] Eres proactivo, propones nuevas ideas y formas de mejorar procesos existentes. Tienes la capacidad de estructurar objetivos en tasks y milestones accionables.
- [ ] Te entusiasma el uso de la tecnología como herramienta para resolver problemas públicos, pero eres consciente de sus riesgos y limitaciones.
- [ ] Valoras la diversidad y la empatía como elementos centrales de una comunidad.

### Deseable 💡

- [ ]  Inglés avanzado 
- [ ]  Experiencia en project management 
- [ ]  Actividad en la comunidad de Codeando México o en otras comunidades 

### Beneficios ❤️

* Trabajar con personas y proyectos que están haciendo una diferencia
* Puedes trabajar de manera remota, con jornadas flexibles y muchas vacaciones
* La cultura de nuestra organización promueve el balance entre el trabajo-vida personal
* Libros, conocimiento y mentores: te facilitamos los recursos que te ayuden a crecer

## Sobre Codeando México 🚀

Codeando México es una comunidad de hackers que busca generar nuevas formas de participación ciudadana a través de la tecnología. Buscamos gobiernos que hagan mejor uso de la tecnología; y aumentar la capacidad de incidencia de la ciudadanía.

Colaboramos con personas de todos los perfiles: activistas, periodistas, funcionarios públicos; diseñadores. Cualquiera que comparta nuestros [principios, valores y código de conducta] (https://github.com/CodeandoMexico/comunidad) puede ser parte de esta comunidad.

### Nuestras redes ✉️

* [GitHub](http://www.github.com/CodeandoMexico)
* [Facebook](http://www.facebook.com/CodeandoMexico)
* [Twitter](http://www.twitter.com/codeandomexico)

## Cómo aplicar ⚡️

Si te interesa formar parte de nuestro equipo puedes aplicar mandando tu CV y una carta motivos a equipo@codeandomexico.org antes del 22 de julio.

**Comment by basicavisual** [comment]
Hola. No quiero aplicar a esto de tiempo completo pero me gustaría involucrarme de algún modo. Con asesoría, mentoría o algún otro tipo de ayuda. Sé que la respuesta puede no quedar ahorita pero lo dejo aquí a su consideración para el largo plazo.
