### ISSUE TITLE
Backend and Front end developers

### ISSUE THREAD

**Issue by luiselizondo** [CodeandoMexico/chambas#5]
# Backend and Front end developers. 

We're looking for very smart people who wants to come works with us and solve great challenges. We're looking for Javascript and Python skills but if you know how to code and are willing to learn super fast, we're interested as well.

If your code makes you feel proud, we're looking for you.

### Detalles 

* 🇲🇽  Guadalajara Mexico
* 🏢  Presencial la mayor parte del tiempo
* 🕐  Tiempo completo
* 📅  As soon as possible
* 💸  We'll negotiate.

### Responsabilidades 💻

* Help the Backend team solve multiple problems and architecture and develop our products.
* Help the Frontend team and work with the UX Designers to create and develop our products.

### Lo que buscamos 💡
- [ ] Javascript / Python
- [ ] Team player
- [ ] Great communication skills
- [ ] Passion

### Beneficios ❤️

* Work with really smart people
* Free meals and Free beer

## Sobre Rever 🚀
We're a SV startup with development offices in Guadalajara, Mexico. Find more about us on http://reverscore.com

### Nuestras redes ✉️

* [Facebook](https://www.facebook.com/reverhq/)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a luis+jobs at reverscore dot com o visita https://reverscore.com/careers.

**Comment by jorgearuv** [comment]
Hi @luiselizondo, is there any Front End Developer position available now?

**Comment by miguelsalazar** [comment]
Cerrado por inactividad.
