### ISSUE TITLE
Programación fullstack senior en Animal Político

### ISSUE THREAD

**Issue by animalpolitico** [CodeandoMexico/chambas#50]
# Vacante en programación full-stack sr.

En Animal Político, Animal MX y Animal Gourmet estamos reclutando para una vacante de tiempo completo.

### Detalles 

* 🇲🇽 Lomas de Chapultepec, CDMX
* 🏢 Presencial
* 🕐 Tiempo completo
* 📅 1 de febrero, 2020
* 💸 A tratar

### ¿De qué va? 💻

* Serás parte de un equipo interdisciplinario (diseño de información, diseño web y periodismo)
* Desarrollarás reportajes especiales e interactivos basados en análisis y visualización de datos
* Darás soporte a nuestros sitios
* Trabajarás en herramientas periodísticas como sinapsis.lat y harás tanto scrapeo como automatización de datos

### Lo que buscamos 💡

- [ ] PHP Vanilla
- [ ] Python
- [ ] JS Vanilla así como frameworks y librerías como React, jQuery, etc.
- [ ] WordPress (creación de temas y plugins desde cero)
- [ ] SASS / LESS 
- [ ] Conocimiento con terminal, NGINX, Apache y mySQL

### Nuestras redes ✉️

* [Facebook](https://www.facebook.com/profile.php?id=215547488473853)
* [Twitter](http://www.twitter.com/pajaropolitico)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, aplica en el [siguiente formulario](https://docs.google.com/forms/d/e/1FAIpQLSdkTsNmYedh9xRSDFpSq9zzTykQddrI12IYj2FkHulvNGnASA/viewform?usp=send_form).

**Comment by almarngl** [comment]
@animalpolitico ¿cerramos este issue?
