### ISSUE TITLE
Desarrollador(a) Full Stack en San Pedro

### ISSUE THREAD

**Issue by monica-guerra** [CodeandoMexico/chambas#52]
# Desarrollador(a) Full Stack

Buscamos a las personas más talentosas y comprometidas para que lideren la estrategia tecnológica del Municipio y juntas resolver problemas públicos de un municipio de más de 133 mil habitantes. Si eres alguien que siempre está buscando problemas desafiantes, no se rinde y estás en busca de poder mejorar directamente la calidad de vida de miles de personas vas a querer unirte a nuestro equipo. 

No solo te enfrentarás a nuevos retos sino también formarás parte de equipo joven de 10 personas donde tendrás la oportunidad de aprender de abogadas, urbanistas, sociólogas, programadoras, arquitectas y economistas. 

### Detalles 

* 🇲🇽  San Pedro Garza García, NL
* 🏢 Trabajo presencial (remoto durante la contingencia)
* 🕐 Tiempo completo
* 📅 01/06/2020
* 💸 40,000

### Responsabilidades 💻

* Coordinar y guiar el desarrollo de proyectos tecnológicos
* Hacer uso y promover las buenas prácticas
* Escribir código limpio y bien probado
* Investigar y proponer las mejores soluciones a retos específicos
* Hacer revisiones y garantizar la calidad de los productos del municipio

### Lo que buscamos 💡

- [ ]  Mínimo 1 año de experiencia trabajando con un framework como Ruby on Rails, Django o Laravel
- [ ]  Buenos fundamentos de programación orientada a objetos
- [ ]  Experiencia en la administración de bases de datos
- [ ]  Experiencia en la creación de APIs
- [ ]  Haber trabajado bajo metodologías ágiles
- [ ]  Muchas ganas de aprender
- [ ]  Disposición a trabajar presencialmente desde las oficinas municipales de San Pedro (una vez terminando la contingencia COVID-19)

## Sobre el equipo en San Pedro🚀

Somos creyentes y nos gusta demostrar que los gobiernos pueden dar soluciones ágiles, de calidad y de alto impacto. No nos gusta reinventar la rueda y siempre estamos aprendiendo e inspirándonos de otras ciudades en el mundo.

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto visita bit.ly/spgg-fullstack y envía tu CV a rolando.drouaillet@sanpedro.gob.mx

**Comment by almarngl** [comment]
Hola @monica-guerra, ¿ya llenaron esta vacante?
