### ISSUE TITLE
Lead de proyectos en Codeando México

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/chambas#57]
## Sobre el puesto 👾

Buscamos una persona entusiasmada por crear soluciones de manera colaborativa ⎼con voluntarios, organizaciones, gobiernos⎼ para atender problemas públicos con tecnología. En Codeando México identificarás problemas públicos (como facilitar el acceso a información sobre COVID, mapear datos de transporte público, investigar estrategias estatales de datos abiertos), idearás y ejecutarás soluciones acompañado de equipos de politólogos, diseñadores, desarrolladores y más. 

### Detalles 

* 🇲🇽    México
* 🏢    Remoto
* 🕐    Tiempo completo
* 📅    Fecha de inicio 1-15 de marzo
* 💸    $ 26,000.00 MXN, negociables según habilidades

### Responsabilidades 💻

* Mapear el status de la tecnología cívica y el gobierno abierto en México e identificar oportunidades de mejora
* Diseñar, gestionar e implementar proyectos de tecnología cívica de manera abierta y colaborativa
* Contribuir al diseño e implementar estrategias para crecer y fortalecer la organización
* Mapear actores estratégicos y facilitar posibilidades de colaboración
* Apoyar transversalmente a las diversas áreas de la organización

### Lo que buscamos 💡

- [ ] Tienes experiencia en coordinación y/o project management de proyectos de tecnología cívica y/o datos
- [ ] Tienes buenas habilidades de comunicación con distintos perfiles profesionales
- [ ] Tienes la capacidad de generar e implementar estrategias para fortalecer y crecer una comunidad. Es un gran plus si has trabajado en proyectos o iniciativas de tecnología cívica y/o datos, o en iniciativas de software libre
- [ ] Eres una persona proactiva, propones nuevas ideas y formas de mejorar procesos existentes. Tienes la capacidad de estructurar objetivos en tasks y milestones accionables.
- [ ] Te entusiasma el uso de la tecnología como herramienta para resolver problemas públicos, pero eres consciente de sus riesgos y limitaciones.

### Deseable

- [ ] Inglés avanzado
- [ ] Has participado en la comunidad de Codeando México o en otras comunidades de tecnología
- [ ] Tienes conocimientos básicos sobre desarrollo web en cualquier lenguaje
- [ ] Entiendes conceptos de desarrollo ágil, y design thinking
- [ ] Aprendes y te adaptas rápido a nuevas tecnologías para resolver problemas técnicos

### Beneficios ❤️

* Trabajar con personas y proyectos que están haciendo una diferencia
* Puedes trabajar de manera remota, con jornadas flexibles y muchas vacaciones
*La cultura de nuestra organización promueve el balance entre el trabajo-vida personal
* Libros, conocimiento y mentores: te facilitamos los recursos que te ayuden a crecer

## Sobre Codeando México 🚀

Codeando México es una comunidad de hackers que busca fortalecer el trabajo e impacto de personas, equipos e instituciones inciden en el espacio público con proyectos de tecnología y datos útiles, accesibles y sustentables.

Cualquiera que comparta nuestros [principios, valores y código de conducta](https://github.com/CodeandoMexico/comunidad) puede ser parte de esta comunidad.

### Nuestras redes ✉️

* [GitHub](http://www.github.com/CodeandoMxico)
* [Facebook](http://www.facebook.com/CodeandoMexico)
* [Twitter](http://www.twitter.com/codeandomexico)

## Cómo aplicar ⚡️

Si te interesa formar parte de nuestro equipo puedes aplicar **mandando tu CV y una carta motivos a equipo@codeandomexico.org antes del 1 de marzo**.

**Comment by arturogg01** [comment]
Hola!
Me interesa mucho esté proyecto y he aplicado!

saludos
