### ISSUE TITLE
Sysadmin para datos.gob.mx

### ISSUE THREAD

**Issue by nez** [CodeandoMexico/chambas#6]
![image](https://cloud.githubusercontent.com/assets/2068301/22910896/b9962114-f222-11e6-805e-bccc334772ff.png)

Datos.gob.mx 🚀 es la plataforma de datos abiertos del Gobierno Federal.
Somos parte del equipo de trabajo de la Estrategia Digital Nacional.
Nos encargamos de desarrollar el portal y diversas herramientas relacionadas con datos abiertos

# Sysadmin

Ingeniero de sistemas para apoyar en la administración de datos.gob.mx

### Detalles 

* 🇲🇽  CDMX
* 🏢  Presencial
* 🕐  Tiempo completo
* 📅  1 de Junio
* 💸  A tratar

### Responsabilidades 💻

* Deployear aplicaciones y mantenimiento
* Revisar y aceptar pull requests
* Dar mantenimiento y hacer playbooks de Ansible

### Lo que buscamos 💡

(Experiencia deseable en)

- [ ] Docker
- [ ] Kubernetes
- [ ] Ansible

### Beneficios ❤️

* Un dia de Home Office
* El trabajo es relevante para el País
* Equipo de trabajo buena onda, retos interesantes y ambiente de aprendizaje

### Nuestras redes ✉️

* [GitHub](http://www.github.com/mxabierto)
* [Facebook](http://www.facebook.com/datosgobmx)
* [Twitter](http://www.twitter.com/datosgobmx)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a andres.gomez@datos.mx, y manda tu CV, Portafolio y/o GitHub

**Comment by miguelsalazar** [comment]
@nez ¿ya se cubrió la vacante?

**Comment by nez** [comment]
@miguelsalazar no se ha cubierto :p
