### ISSUE TITLE
Intern de Tecnología en Codeando México

### ISSUE THREAD

**Issue by ricardomiron** [CodeandoMexico/chambas#60]
# Intern de Tecnología 

## Sobre la organización 🚀
Codeando México es una comunidad de hackers cívicos que busca fortalecer el trabajo e impacto de personas, equipos e instituciones inciden en el espacio público con proyectos de tecnología y datos útiles, accesibles y sustentables.

Cualquiera que comparta nuestros principios, valores y [código de conducta](https://github.com/CodeandoMexico/comunidad/blob/master/CODIGO-DE-CONDUCTA.md) puede ser parte de esta comunidad.

## Sobre el puesto 👾
Buscamos una persona entusiasmada por crear soluciones de manera colaborativa ⎼con voluntarios, organizaciones, gobiernos⎼ para atender problemas públicos con tecnología. 

Si tienes 15-20 horas semanales disponibles para colaborar con nosotras y estás buscando generar experiencia, participar en comunidades, practicar tus habilidades técnicas / coordinación de proyectos tecnológicos, conocer más sobre tecnología cívica o hacer prácticas profesionales. ¡Queremos saber de ti!

### Detalles 

* 🇲🇽 México
* 🏢 Remoto 
* 🕐 Medio tiempo (15-20 horas semanales)
* 📅 Duración 1 de octubre a 31 de diciembre (3 meses)
* 💸 $6,000 - $7,000 MXN mensuales

### Responsabilidades 💻

* Participar en los proyectos de la comunidad, gestionando la colaboración y las contribuciones
* Desarrollar e implementar funcionalidades para proyectos nuevos o existentes, utilizando distintas herramientas tecnológicas o lenguajes de programación
* Generar y mejorar la documentación de proyectos de software open source
* Apoyar transversalmente en las actividades de la organización y brindar apoyo cuando sea necesario

### Lo que buscamos 💡

- [ ] Entiendes términos técnicos y tienes conocimiento básico sobre desarrollo de software, lógica computacional y/o sistemas
- [ ] Aprendes y te adaptas rápido a nuevas tecnologías para resolver problemas técnicos
- [ ] Eres una persona proactiva, propones nuevas ideas y formas de mejorar procesos existentes
- [ ] Te entusiasma el uso de la tecnología como herramienta para resolver problemas públicos, pero eres consciente de sus riesgos y limitaciones

### Deseable
- [ ] Tienes conocimiento básicos sobre desarrollo de software (Git/ GitHub/ APIs/ otras) y/o
- [ ] Tienes conocimientos básicos sobre tecnologías web (HTML/ CSS/ JS/ otros) y/o
- [ ] Tienes conocimientos básicos sobre ciencia de datos (Python/ R/ otros)
- [ ] Has participado en comunidades tecnológicas

¡Pero estamos abiertos a cosas nuevas! Estas habilidades son enunciativas, más no limitativas. Queremos que el ser parte del equipo sea un proceso retador y de aprendizaje, no tengas miedo de aplicar a la oportunidad incluso si no eres un experto o consideras que alguna de las habilidades no está tan desarrollada, podemos aprender juntos.

### Beneficios ❤️

* Trabajar con personas y proyectos que están haciendo una diferencia
* Queremos apoyarte a desarrollar tus habilidades, buscaremos mentores que te ayuden a lograr tus objetivos
* Retroalimentamos de manera clara y directa, enfocándonos en generar un aprendizaje
* Libros, conocimiento y mentores: te facilitamos los recursos que te ayuden a crecer

### Nuestras redes ✉️

* [GitHub](http://www.github.com/CodeandoMxico)
* [Facebook](http://www.facebook.com/CodeandoMexico)
* [Twitter](http://www.twitter.com/codeandomexico)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, llena este formulario antes del 24 de septiembre: 
https://airtable.com/shrGcDpZKDK8Rrj78

**Comment by DARWINDEV** [comment]
Buenas!! Disculpen en qué fecha se liberan los resultados de la convocatoria? Saludos 🤟

**Comment by JosBenn1** [comment]
Hola!!, cuando sabremos quienes fueron aceptados?
Gracias!!

**Comment by ricardomiron** [comment]
Hola, ya estamos mandando las respuestas :) entre hoy y este fin de semana deberían recibir un correo

**Comment by JosBenn1** [comment]
Gracias!!
Quedamos pendientes al correo! :)

**Comment by rodrigocrz** [comment]
Hola que tal, buen día.

A alguien le llegó algún correo durante el fin de semana? :(

**Comment by JoseCCorona** [comment]
Aún no estimado,

Hay que seguir siendo pacientes

Saludos!

Get Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ricardomiron** [comment]
Hola, de nuevo :) a la gran mayoría ya le enviamos respuesta solo de los que entrevistamos por ahí aún tenemos varios pendientes porque seguimos en el proceso de selección. Pero esta semana ya cerraremos así que deberían recibir noticias muy pronto.
