### ISSUE TITLE
Ingeniero de API para datos.gob.mx

### ISSUE THREAD

**Issue by nez** [CodeandoMexico/chambas#7]
![image](https://cloud.githubusercontent.com/assets/2068301/22910896/b9962114-f222-11e6-805e-bccc334772ff.png)

Datos.gob.mx 🚀 es la plataforma de datos abiertos del Gobierno Federal.
Somos parte del equipo de trabajo de la Estrategia Digital Nacional.
Nos encargamos de desarrollar el portal y diversas herramientas relacionadas con datos abiertos

# Ingeniero de APIs

Ingeniero de APIs para disponibilizar datos abiertos en API, dar mantenimiento a las bases de datos correspondientes.

### Detalles 

* 🇲🇽  CDMX
* 🏢  Presencial
* 🕐  Tiempo completo o tiempo parcial
* 📅  1 de Junio
* 💸  A tratar

### Responsabilidades 💻

* Administrar los datos de api.datos.gob.mx (la BD Mongo y sus agentes)
* Gestionar con DreamFactory la plataforma centralizada de APIs
* ETL de bases de datos

### Lo que buscamos 💡

(Experiencia deseable en)

- [ ] Mongodb
- [ ] Postgres
- [ ] APIs REST

### Beneficios ❤️

* Un dia de Home Office
* El trabajo es relevante para el País
* Equipo de trabajo buena onda, retos interesantes y ambiente de aprendizaje

### Nuestras redes ✉️

* [GitHub](http://www.github.com/mxabierto)
* [Facebook](http://www.facebook.com/datosgobmx)
* [Twitter](http://www.twitter.com/datosgobmx)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a andres.gomez@datos.mx, y manda tu CV, Portafolio y/o GitHub

**Comment by miguelsalazar** [comment]
@nes ¿ya se cubrió la vacante?

**Comment by nez** [comment]
si @miguelsalazar gracias!
