### ISSUE TITLE
Ingeniero de Visualización de Datos para datos.gob.mx

### ISSUE THREAD

**Issue by nez** [CodeandoMexico/chambas#8]
![image](https://cloud.githubusercontent.com/assets/2068301/22910896/b9962114-f222-11e6-805e-bccc334772ff.png)

Datos.gob.mx 🚀 es la plataforma de datos abiertos del Gobierno Federal.
Somos parte del equipo de trabajo de la Estrategia Digital Nacional.
Nos encargamos de desarrollar el portal y diversas herramientas relacionadas con datos abiertos

# Ingeniero de Visualización de Datos

Trabajarás generando visualizaciones interactivas como mapas, grafos y otro tipo de charts 

### Detalles 

* 🇲🇽  CDMX
* 🏢  Presencial
* 🕐  Tiempo completo
* 📅  1 de Junio
* 💸  A tratar

### Lo que buscamos 💡

(Experiencia deseable en)

- [ ] D3
- [ ] Postgres
- [ ] MongoDB
- [ ] Estadística descriptiva

### Beneficios ❤️

* Un dia de Home Office
* El trabajo es relevante para el País
* Equipo de trabajo buena onda, retos interesantes y ambiente de aprendizaje

### Nuestras redes ✉️

* [GitHub](http://www.github.com/mxabierto)
* [Facebook](http://www.facebook.com/datosgobmx)
* [Twitter](http://www.twitter.com/datosgobmx)

## Cómo aplicar ⚡️

Si te interesa aplicar a este puesto, escribe a andres.gomez@datos.mx, y manda tu CV, Portafolio y/o GitHub

**Comment by miguelsalazar** [comment]
@nes ¿ya se cubrió la vacante?

**Comment by nez** [comment]
@miguelsalazar ya no es necesario. grs
