### ISSUE TITLE
Programadores para Mediateca INAH

### ISSUE THREAD

**Issue by mariellgtz** [CodeandoMexico/chambas#9]
# Programador para Mediateca INAH

Somos el área del Instituto Nacional de Antropología e Historia encargada de diseñar, desarrollar y administrar, entre otras plataformas, el repositorio digital del patrimonio histórico de México.
Buscamos programadores para la migración, administración y visualización de datos, desarrollo de módulos en Drupal, desarrollo de herramientas en PHP y HTML5

##Detalles

* 🇲🇽  Colonia Condesa, Ciudad de México
* 🏢  Presencial. Horario : 9:30 a 6:00 y viernes de 9:30 a 3:00
* 🕐  Tiempo completo
* 💸  17,000 a 24,000 libres según aptitutdes

### Responsabilidades 💻

- Migración, administración y visualización de datos, desarrollo de módulos en Drupal.

### Lo que buscamos 💡

- Tener experiencia en el manejo de:
- Servidores UNIX (herramientas)
- PHP
- XML
- MySQL
- HTML5
- Drupal

##  Mediateca INAH 🚀

Somos el área del Instituto Nacional de Antropología e Historia encargada de diseñar, desarrollar y administrar, entre otras plataformas, el repositorio digital del patrimonio histórico de México.

### Nuestras redes ✉️

* https://www.facebook.com/INAHmx/?fref=nf
* http://www.inah.gob.mx/es/

## Cómo aplicar ⚡️
Interesados enviar currículum a jimena_escobar@inah.gob.mx

**Comment by miguelsalazar** [comment]
Cerrado por inactividad.
